#! /bin/bash

export PATH="/home/paul/bin/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

cd /home/paul/dev/testqt
git fetch

### if [ $(git rev-parse @{u}) = $(git rev-parse @) ]; then
###     date
###     echo "___________________ NOTHING TO DO, EXITING _____________________"
###     exit 0
### fi


###git pull
##git submodule update

git submodule foreach git pull --rebase
git submodule foreach git submodule update

git clean -fdx

export CCACHE_NODIRECT="1"

export MAKEFLAGS="-j9"

echo "_________________ STARTING UP ___________________________"

date
git rev-parse @

nice python3 /home/paul/dev/ex/git/feature-test/test.py $(date +%Y-%m-%dT%H:%M)

cp /home/paul/dev/ex/git/feature-test/index.html /var/www/html/featuretest
cp `ls -t /home/paul/dev/ex/git/feature-test/featuretest_*.html |head -1` /var/www/html/featuretest

date

echo "___________________ OVER AND OUT _____________________________"
